### ISSUE TITLE
Failed Job - ImportMastodonFollowersJob

### ISSUE THREAD

**Issue by kurucu** [inovector/mixpost#87]
### Steps to reproduce the problem

1. Attempt to import followers

### Expected behaviour

The job should run and import followers

### Actual behaviour

It fails with "Undefined array key 'client_id'"

### Detailed description

ErrorException: Undefined array key "client_id" in /.../vendor/inovector/mixpost-pro-team/src/Abstracts/SocialProviderManager.php:47

### Specifications

PHP | 8.2.14
Laravel | 10.48.4
Horizon | 5.23.2.0
Mixpost | 2.0.2.0
Mixpost Enterprise | 2.0.0.0

**Comment by lao9s** [comment]
Thank you for reporting. 
I'll check it and fix as soon as possible!

**Comment by lao9s** [comment]
@kurucu `Abstracts/SocialProviderManager.php:47` is an empty line. Maybe you did not terminate Horizon after upgrading?

**Comment by kurucu** [comment]
@lao9s That's part of the deploy script, and also I can see I tried that before raising this ticket manually 😂 

So no, that's not it. Tried again just now, to make sure.

**Comment by kurucu** [comment]
> @kurucu do you use Docker?

No, straight server.

**Comment by kurucu** [comment]
Copying a few more lines from the console output in case they help.

```
Exception
ErrorException: Undefined array key "client_id" in /home/mixpost-app/vendor/inovector/mixpost-pro-team/src/Abstracts/SocialProviderManager.php:47
Stack trace:
#0 /home/mixpost-app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/mixpost-app/vendor/inovector/mixpost-pro-team/src/Abstracts/SocialProviderManager.php(47): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /home/mixpost-app/vendor/inovector/mixpost-pro-team/src/SocialProviderManager.php(151): Inovector\Mixpost\Abstracts\SocialProviderManager->buildConnectionProvider()
#3 /home/mixpost-app/vendor/inovector/mixpost-pro-team/src/Abstracts/SocialProviderManager.php(39): Inovector\Mixpost\SocialProviderManager->connectMastodonProvider()
#4 /home/mixpost-app/vendor/inovector/mixpost-pro-team/src/Abstracts/SocialProviderManager.php(26): Inovector\Mixpost\Abstracts\SocialProviderManager->createConnection()
#5 /home/mixpost-app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Inovector\Mixpost\Abstracts\SocialProviderManager->connect()
#6 /home/mixpost-app/vendor/inovector/mixpost-pro-team/src/Concerns/UsesSocialProviderManager.php(13): Illuminate\Support\Facades\Facade::__callStatic()
#7 /home/mixpost-app/vendor/inovector/mixpost-pro-team/src/SocialProviders/Mastodon/Jobs/ImportMastodonFollowersJob.php(58): Inovector\Mixpost\SocialProviders\Mastodon\Jobs\ImportMastodonFollowersJob->connectProvider()
```

**Comment by kurucu** [comment]
Hey @lao9s. I'm still getting this fail constantly, and for many user accounts.

I've also seen that `ImportMastodonPostsJob` is also failing, with a similar error. I've reset all cache, and restarted all services.

The primary error is still:

```
ErrorException: Undefined array key "client_id" in vendor/inovector/mixpost-pro-team/src/Abstracts/SocialProviderManager.php:47
```

All of my dependencies are up to date, and I can find a relevant line at that location.

```
    protected function buildConnectionProvider(string $provider, array $config): SocialProvider
    {
        $connection = (new $provider($this->container->make('request'), $config['client_id'], $config['client_secret'], $config['redirect'], array_merge($this->values, $config['values'] ?? []))); // THIS IS LINE 47

        if (!$connection instanceof SocialProvider) {
            throw new \Exception('The provider must be an instance of SocialProvider');
        }

        return $connection;
    }
```

**Comment by lao9s** [comment]
@kurucu 

Maybe this can help you: https://docs.mixpost.app/troubleshooting#mastodon-connection-issue

If not, I'll debug your app.

**Comment by kurucu** [comment]
Hey Dima,

I've tried it on one account to see what happens, just because of this:

> This action may have a negative impact on scheduled posts and authenticated accounts with Mastodon on troet.cafe server.

What would cause this step to be needed? Once I see what happens there, I'll let you know.

If that is the problem, do I need to get all my users to reconnect? Multiple accounts are affected. Can any of this be automated if so, and if not, could users be automatically be notified if they are affected?

**Comment by lao9s** [comment]
@kurucu Users need to reconnect their accounts.
